### ISSUE TITLE
Bug: Navigating to examples/extension-epic-mode throws an error and white page of death

### ISSUE THREAD

**Issue by charlex** [ifiokjr/remirror#112]
## Description

URL: https://docs.remirror.org/examples/extension-epic-mode

I am seeing this in Chrome (75.0.3770.142) and Firefox (68 and 68.0.1 as well).

<img width="760" alt="Screen Shot 2019-07-20 at 10 37 49 PM" src="https://user-images.githubusercontent.com/1542740/61584873-0663bd80-ab3f-11e9-9851-705daa98ef08.png">

Errors:

```
TypeError: "this.container.appendChild is not a function"
    value extension-epic-mode.esm.js:266
    view extension-epic-mode.esm.js:400
    updatePluginViews index.js:4476
    St index.js:4339
    v react-ssr.esm.js:116
    React 13
    safeSetState loadable.esm.js:164
    promise loadable.esm.js:223
react-dom.production.min.js:198:186
TypeError: "this.container.appendChild is not a function"
    value extension-epic-mode.esm.js:266
    view extension-epic-mode.esm.js:400
    updatePluginViews index.js:4476
    St index.js:4339
    v react-ssr.esm.js:116
    React 13
    safeSetState loadable.esm.js:164
    promise loadable.esm.js:223
react-dom.production.min.js:198:186
```

## Possible Fix

In general, a [react error boundary](https://reactjs.org/docs/error-boundaries.html) at the page-level could allow a single page to fail without causing a white page of death.

Specifically, I'm not exactly sure how to fix a missing container like this.

**Comment by charlex** [comment]
Another possible fix (and enhancement) would be to try and use Docz's `<Playground />` comp which might bring with it, its own error boundary. This could be used to wrap any code examples, and have the added benefit of showing the code inline in the docs! (See the Docz screenshot and snippet of the Playground usage on their homepage: https://www.docz.site/)

 But if `<Playground />` doesn't have an error boundary, we could wrap a Playground in an error boundary and do it ourselves. Or of course offer to merge an error boundary directly into the Docz repo.

**Comment by ifiokjr** [comment]
@charlex Thanks for raising this. I'll see if I can find out what's going on.
