### ISSUE TITLE
Feature: Allow additional attributes to be parsed for links

### ISSUE THREAD

**Issue by charlex** [ifiokjr/remirror#113]
## Description

Currently, Remirror *writes* all attributes in `LinkExtension.schema.toDOM()`, but only *reads* the `href` attribute. My usecase is to support the `title` attribute, but I could imagine a world in which options could be passed to support arbitrary attributes for any usecase.

## Possible Implementation

This could be included in the LinkExtension to accept an array of whitelisted attributes to support.

I went ahead and created my own extension off of the LinkExtension, which is pretty elegant as a solution from my viewpoint:

```ts
import { Cast, MarkExtensionSpec } from '@remirror/core';
import { LinkExtension } from '@remirror/core-extensions';

export class MyLinkExtension extends LinkExtension {
  get schema(): MarkExtensionSpec {
    return {
      attrs: {
        href: {
          default: null,
        },
        title: {
          default: null,
        },
      },
      inclusive: false,
      parseDOM: [
        {
          getAttrs: node => ({
            href: Cast<Element>(node).getAttribute('href'),
            title: Cast<Element>(node).getAttribute('title'),
          }),
          tag: 'a[href]',
        },
      ],
      toDOM: node => [
        'a',
        {
          ...node.attrs,
          rel: 'noopener noreferrer nofollow',
        },
        0,
      ],
    };
  }
}
```

**Comment by ifiokjr** [comment]
@charlex nice suggestion 👍 

I previously created the `extraAttrs` `BaseExtenion` option to solve this problem. Theoretically, it is available on every `(Node/Mark)Extension`, although currently implemented for the `MentionExtension`. Improving this functionality, and making it a standard for all `core-extensions` might solve the problem you're facing without needing to extend the extension. 

#### Type definition

https://github.com/ifiokjr/remirror/blob/master/%40remirror/core/src/types/base.ts#L188-L200

#### Current implementation

https://github.com/ifiokjr/remirror/blob/5889193104cc98745d78c87eb9f6bf7d3687bf1d/%40remirror/extension-mention/src/mention-extension.ts#L63-L71

#### Current limitations

- No parsing
- Attributes can't be required (although thinking about it this may have to remain true).

I've got a small PR which I'll push in a few hours which adds parsing functionality. I'd certainly be interested in your feedback.
