### ISSUE TITLE
Add example: `with-gatsby`

### ISSUE THREAD

**Issue by ifiokjr** [ifiokjr/remirror#117]
## Description

Add the simplest possible example of how to use this library with [gatsby](https://github.com/gatsbyjs/gatsby).

This issue is open to anyone and could serve as a fun introduction to `remirror` 😄 

## Possible Implementation

Take a look at the current [`with-next`](https://github.com/ifiokjr/remirror/tree/master/examples/with-next) and [`with-razzle`](https://github.com/ifiokjr/remirror/tree/master/examples/with-razzle) implementations.

**Comment by alexluong** [comment]
Hey I'd like to help with this. Is there a date you'd like to get this done before?

**Comment by ifiokjr** [comment]
@alexluong that would be brilliant. There's no particular date I have in mind although sooner is better than later.

**Comment by alexluong** [comment]
@ifiokjr Yeah I'm working on a theme for Gatsby ThemeJam which ends on July 31st. I can get started with this right after!

**Comment by ifiokjr** [comment]
> @ifiokjr Yeah I'm working on a theme for Gatsby ThemeJam which ends on July 31st. I can get started with this right after!

Nice 👍

**Comment by ifiokjr** [comment]
Since the docs are now built with gatsby, this is no longer required.
