### ISSUE TITLE
SSR of nested toDOM extensions is ordered improperly

### ISSUE THREAD

**Issue by jashmenn** [ifiokjr/remirror#125]
I've hit an interesting bug that I'm not sure how to fix: 

SSR for nested `toDOM` in extensions seems to order improperly - even though it renders fine once JavaScript loads. The result of this bug is that any nodes that require a nested DOM rendering don't SSR properly.

Here are the details (links to runnable code below):

## The extension

Say we have an extension that has a `toDOM` of the following in `schema()`:

```javascript
      toDOM() {
        const attrs = {
          'data-foo-type': 'true',
        };
        return ['div', attrs, ['div', { class: 'inside' }, 0]];
      },
```

Notice that we have an outer `div[data-foo-type]` which is parent to `div.inside`, which has the hole.

## The document

Say this Extension allows `content: "block*"` and we put a paragraph child in the hole with the following document:

```javascript
const initialJson = {
  type: 'doc',
  content: [
    {
      type: 'foo',
      content: [
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'This is the foo thing',
            },
          ],
        },
      ],
    },
  ],
};
```

## The result _after_ SSR

This renders just as you would expect, with the paragraph text within `div.inside`:

![Screenshot 2019-07-24 11 07 54](https://user-images.githubusercontent.com/4318/61810621-3cd25e80-ae05-11e9-98bb-f9eebb1c149b.png)

## The result rendered by _SSR_ (the bug)

However, the SSR rendered version is the following:

![Screenshot 2019-07-24 11 23 15](https://user-images.githubusercontent.com/4318/61810724-7a36ec00-ae05-11e9-97e1-1262cf1e27e3.png)

That is, the `paragraph` **is a sibling** of `div.inside` (!).

## The Code

You can see the runnable code for this example [in my branch here](https://github.com/fullstackio/remirror/blob/bug/nested-dom-ssr/examples/with-next/pages/editor/simple.tsx).

> If you checkout that branch `bug/nested-dom-ssr` the code should run and you can visit http://localhost:3000/editor/simple

## The Solution

I'm not sure! Any suggestions?

**Comment by ifiokjr** [comment]
Hi, @jashmenn thanks for raising this 👍 

This was fixed in `@remirror/react-renderer@0.4.x`. I stumbled across it when working on the new `codeBlock` component and here's the commit which fixed the issue https://github.com/ifiokjr/remirror/commit/a353718dba352d1914d2f51602d9b566e918bd98.

I think the only solution is to upgrade. However, when upgrading, please note that there've been a number of breaking changes as outlined [here](https://github.com/ifiokjr/remirror/blob/canary/changelog.md#040---2019-07-22)
