### ISSUE TITLE
Move from custom tslint setup to `@typescript-eslint/eslint-plugin`

### ISSUE THREAD

**Issue by ifiokjr** [ifiokjr/remirror#134]
## Description

TSLint is being phased out by the TypeScript team in favour of ESLint. It'd be nice to also move with the community and embrace this change. 

## Possible Implementation

The [docs](https://github.com/typescript-eslint/typescript-eslint) are very good and the only thing that held me back in the past was the lack of a drop-in replacement for `ordered-imports`. However, I can probably live without it.

## Checklist

- [x] I have read the [**contributing**][contributing] document.

[contributing]: https://github.com/ifiokjr/remirror/blob/master/docs/pages/contributing.md

**Comment by charlex** [comment]
I just did this for my project, I'll see if I can get this going for Remirror.

**Comment by charlex** [comment]
@ifiokjr When I did this for my project (also a TS monorepo), I ended up ripping out much of per-package tslint stuff I had, and running eslint at the root level. Seems to have simplified most of my package.json files, and when I need to update the linting packages or scripts, I can do so simply at the root. 

I suppose the thing I'm losing is that more granular control, but I've never needed that level of granularity at the package level.

Thoughts on this?

**Comment by ifiokjr** [comment]
@charlex that sounds good. 

Currently, linting commands take a long time to complete since each package has its own separate lint command. Some of the previous [tslint rules](https://github.com/kickjump/tslint-rules/blob/master/base.json) required a `tsconfig` file to run. 

If eslint makes it easier to get away from this then that's great news. 


One rule I'm keen to replicate is [tslint-no-circular-imports](https://github.com/bcherny/tslint-no-circular-imports). I know the [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-cycle.md) library has a similar rule, but I've never checked if it can work with typescript.

Finally, if you need help with getting the [travis](https://github.com/ifiokjr/remirror/blob/canary/.travis.yml) and [azure](https://github.com/ifiokjr/remirror/blob/canary/support/azure/azure-pipelines.yml) configurations to work let me know and I can hop onto the PR with you.

**Comment by charlex** [comment]
@ifiokjr It's been my experiencing that Typescript won't build a project if there is a circular dependency. I don't have any screenshots or documentation handy to replicate this behavior. 

If at build time TS just refused to build, wouldn't this suffice in lieu of tslint-no-circular-imports, or am I not following?

**Comment by ifiokjr** [comment]
> @ifiokjr It's been my experiencing that Typescript won't build a project if there is a circular dependency. I don't have any screenshots or documentation handy to replicate this behavior.

@charlex I haven't found this to be the case. For example, this [example repo](https://github.com/ifiokjr/ts-circular-dependency) still builds even with the circular dependency. I've had some bad experiences with circular dependencies in the past. They don't always cause errors, but when they do, the errors are cryptic and difficult to track down.

It may be the case that the issues I faced before with circular dependencies no longer exist so I'm open to excluding the lint rule if we can verify that the protections are now built-in.

**Comment by ifiokjr** [comment]
This has been addressed by #150 

Thanks for your support and contributions @charlex 😊
