### ISSUE TITLE
React Renderer should optionally support a default type

### ISSUE THREAD

**Issue by hennessyevan** [ifiokjr/remirror#137]
## Description

The React Renderer will skip over types (when `skipUnknownTypes` is specified) if they don't exist but that currently filters out strings whereas the core editor allows for a `stringHandler` prop to transform string inputs into valid prosemirror documents.

## Possible Fix

Add a `defaultType` prop to the `RenderTree` component that will supply the given type after checking for a `TypeHandler` at https://github.com/ifiokjr/remirror/blob/master/%40remirror/renderer-react/src/renderer.tsx#L127 

```tsx
<RenderTree
  defaultType={string | React.ComponentType}
/>
```

I'll open a PR for it tomorrow 👍 

## Checklist

- [x] I have read the [**contributing**][contributing] document.

[contributing]: https://github.com/ifiokjr/remirror/blob/master/docs/pages/contributing.md

**Comment by ifiokjr** [comment]
The `stringHandler` is actually for converting a string into a prosemirror document. It really doesn't come into play within the `react-renderer`.

The react renderer is purely for converting the prosemirror node (or in reality the JSON from the prosemirror node) into a react tree. If it's a string e.g. markdown the library user should use a markdown library to convert to their desired react component tree.

I'm closing for now, but I may also have misunderstood the issue so I'm happy to open again if my understanding is off.
