### ISSUE TITLE
Add support for `all-contributors`

### ISSUE THREAD

**Issue by ifiokjr** [ifiokjr/remirror#143]
## Description

Add support for [`all-contributors`](https://github.com/all-contributors/all-contributors) to the repository. I've never done so before so would be happy to have someone else implement or at least receive pointers on how it can be done.

**Comment by aarongreenlee** [comment]
I looked into this but it looks like you must have sufficient rights to install the bot into the repo. Setup is rather straight forward from there. The boy will even modify the readme to setup the initial table. Once installed it is maintained by mentioning the bot in a comment and sending commands to recognize contributors and their contribution type(s).

**Comment by ifiokjr** [comment]
@aarongreenlee thanks for looking into this. I've added you as a contributor. Does that make it possible?

**Comment by ifiokjr** [comment]
All sorted 😄
