### ISSUE TITLE
3 E2E tests failing (code formatting)

### ISSUE THREAD

**Issue by benjie** [ifiokjr/remirror#146]
## Description

Hey, three of the E2E tests are failing for me (all the other tests pass); wanted to check if this was expected, or if there's something wrong with my setup?

![Screenshot_20190809_141550](https://user-images.githubusercontent.com/129910/62781692-71eeda00-bab0-11e9-8a94-c7c2114d6bd7.png)

## Checklist

- [x] I have read the [**contributing**][contributing] document.

[contributing]: https://github.com/ifiokjr/remirror/blob/master/docs/pages/contributing.md

**Comment by ifiokjr** [comment]
@benjie are you on a windows machine? I've only run the test suite on mac. I was meaning to test out the shortcuts that are being used to trigger that command. 

This is the key modifier being used to test and perhaps it's not correct for windows.

https://github.com/ifiokjr/remirror/blob/7d30fbcfb39e549dc3ca4e9dd9f230b135fc9f88/%40remirror/core/src/helpers/keys.ts#L36

If we add an integration test for windows on Azure that should help fix/diagnose future issues.

**Comment by benjie** [comment]
I'm on Linux actually; recently switched back after a decade on Mac.

If I go to https://docs.remirror.org/showcase/wysiwyg and type in

````
```ts const a = 1; const b = 2;
````

and then press alt-shift-f then it does format. How can I debug the tests? (They run invisibly for me.)

**Comment by ifiokjr** [comment]
You can try.

```bash
yarn test:e2e:debug
```

That will launch the browser visibly and run the tests.
