### ISSUE TITLE
Themes Not Working (Emotion Configuration)

### ISSUE THREAD

**Issue by aarongreenlee** [ifiokjr/remirror#170]
## Symptom

Styles, themes, and perhaps even the white-space character are not rendering. The console may also show an error such as:

```
Warning: Invalid value for prop `css` on <div>
```

**Problems**

1. White-space cannot be added to the end of input (the focus of this issue; see animation; in FireFox but not Chrome)
2. The theme does not work for the editor.

## Recording of White-Space Issue
![Screen Recording 2019-11-05 at 06 29 AM](https://user-images.githubusercontent.com/264508/68204444-0379c500-ff96-11e9-94c1-63da50bb3630.gif)

## Possible Solution

Ensure you have properly configured the `emotion` library to use the `css` prop. This dependency requires changes to your babel configuration or notations to be added to all source files which use the `css` prop. See https://emotion.sh/docs/install.

## Background

I've made several attempts over the last few days to assemble the showcase WYSIWYG editor directly in my application to provide me with a starting point for working on my own extensions.  If I import the showcase WYSIWYG editor directly into my application the issues does not occur.

## Source Code

This morning, I was determined to find the cause and created another repository ([github.com/aarongreenlee/remirror-space-issue](https://github.com/aarongreenlee/remirror-space-issue)) with a simplified editor and surrounding application and find the issue continues to persist. I hope this application is helpful and allows for the issue to be reproduced and isolated.

## Checklist

- [x] I have read the [**contributing**][contributing] document.

[contributing]: https://github.com/ifiokjr/remirror/blob/canary/docs/pages/contributing.md

## Thank You

Thank you for taking the time to review this issue. I'm hoping there is some small step I am missing. Once I understand where I am going wrong I'll contribute back a step by step guide to aid others in building their own WYSIWYG editor.

---

## Simplified Assembly showing White-Space Issue

For convenience, here is an extract from the [repository](https://github.com/aarongreenlee/remirror-space-issue) I've shared where I produce this issue. The repository shares a similar extract of the full wysiwyg editor I've ported this morning which shows the same issue.

```ts
import {
    ManagedRemirrorProvider,
    RemirrorManager,
    useRemirrorContext,
} from "@remirror/react";

import React, { FC } from "react";
import { WysiwygEditorProps, WysiwygExtensions } from "../wysiwyg-types";

export const WysiwygEditor: FC<WysiwygEditorProps> = (
    {
        defaultLanguage,
        children,
        ...props
    },
) => {

    return (
        <RemirrorManager>
            <ManagedRemirrorProvider {...props}>
                <>
                    <InnerEditor/>
                    {children}
                </>
            </ManagedRemirrorProvider>
        </RemirrorManager>
    )
};

/**
 * The internal editor responsible for the editor layout and ui.
 * Any component rendered has access to the remirror context.
 */
const InnerEditor: FC = () => {
    const { getRootProps } = useRemirrorContext<WysiwygExtensions>();

    return (
        <div {...getRootProps()} data-testid='remirror-wysiwyg-editor'/>
    )
};
```

**Comment by aarongreenlee** [comment]
I observe my example is working in Chrome but not FireFox. I am now investigating after [reading this post from the Prosemirror board](https://discuss.prosemirror.net/t/firefox-space-insertion-behavior-during-typing/810/3).

**Comment by aarongreenlee** [comment]
## Solution

I was not importing the Prosemirror CSS file. Specifically, this CSS resolves the issue:

```css
.ProseMirror {
  word-wrap: break-word;
  white-space: pre-wrap;  // this is the line that resolved the issue
  -webkit-font-variant-ligatures: none;
  font-variant-ligatures: none;
}
```

Now, I will continue to explore **why** the theme itself is not working when I assemble the editor directory. The `white-space` rule listed above should be applied from remirror's `baseTheme`.

**Comment by aarongreenlee** [comment]
I'm convinced I don't have the proper setup for `emotion` and am now working to configure it. This is no doubt observable in the repository I've shared after looking through the emotion documentation and looking at my babel configuration.

I moved from styled-components to emotion a few weeks ago in my main app and was delighted the migration was straight forward; however, I was using the `styled.div` syntax and I see some additional work is required to use the `css` prop style which is used by remirror. See https://emotion.sh/docs/install.

I've revised the description to show a symptom of this issue is the following error in my console:

```
Warning: Invalid value for prop `css` on <div> ...
```

**Comment by aarongreenlee** [comment]
I've gone through my configuration several times. I think there is an issue with themes when using the `ts-loader` for webpack possibly related to this [open emotion pull request](https://github.com/emotion-js/emotion/pull/1220).

**Comment by dj0nes** [comment]
> Warning: Invalid value for prop `css` on <div> ...

Thanks for posting about this @aarongreenlee, I'm seeing the same issue with the wysiwyg editor components and emotion + babel plugin.

Oddly, adding the jsx pragma to the `wysiwyg` source files (copied straight out of @remirror/editor-wysiwyg/src/components) fixes the issue for me.

```js
/** @jsx jsx */
import { jsx } from '@emotion/core'
```

**Comment by aarongreenlee** [comment]
Agreed, @dj0nes. I have been trying to get the babel presets to work so the core extensions don't need modification; however, I think may want to modify the core so folks can assemble with create-react-app which won't let you customize babel.

**Comment by aarongreenlee** [comment]
I've opened a pull request to convert to using the JSX pragma explicitly. This change will avoid adding documentation which complicates adoption by asking folks to modify their build setup.

**Comment by ifiokjr** [comment]
Thanks for raising this @aarongreenlee
