### ISSUE TITLE
Cmd-Delete into any node only deletes the node and not the whole line (⌘ + ⌫)

### ISSUE THREAD

**Issue by ifiokjr** [ifiokjr/remirror#44]
## Description

When backspacing into a node with the Cmd-key (⌘ + ⌫) it should delete the whole line. However, at the moment it only deletes the emoji or mention node directly before the cursor.

**Comment by benjie** [comment]
Haven't read the diff, just wanted to check that this works for non-Mac OS also (i.e. uses Ctrl instead of Cmd on non-Mac OS).

**Comment by ifiokjr** [comment]
I'll have to test this out. I wasn't aware of the `ctrl-del` shortcut on windows. 

I'll set up windows as an **e2e** test environment in the next PR and see what happens. The tests seem a lot less flakey now. 

The main reason I marked this as fixed is that the two prosemirrer nodes which caused problems within remirror, `mention`'s and `emoji` are no longer nodes and no longer suffer from that problem. I haven't really investigated it as a general fix.

**Comment by benjie** [comment]
I misread the issue; ignore my above comment. On linux ctrl-backspace is equivalent to alt-backspace on Mac (delete word).
