### ISSUE TITLE
Upgrade docz to v1

### ISSUE THREAD

**Issue by ifiokjr** [ifiokjr/remirror#65]
## Detailed Description

Implement the new docz version following the [migration guide](https://github.com/pedronauck/docz/blob/master/MIGRATION_GUIDE.md)

- Upgrade to v1
- Explore different themes

**Comment by 100ideas** [comment]
I took a shot at upgrading docz to v1.0.0-rc.1.

I couldn't get it to work, but my impression is that docz@v1 has better built-in support for typescript codebased, so potentially docz-babel-webpack configuration might not need to be so involved.

Took a bunch of notes: https://github.com/100ideas/remirror/blob/doczv1/support/docz-v1-WIP-notes/NOTES-docz-v1.0.0-experiments.md

**Comment by 100ideas** [comment]
here's a screenshot of `docz@v1.0.0-rc.1`[/examples/typescript](https://github.com/pedronauck/docz/tree/master/examples/typescript) running w/ a copy of remirror/docs/examples/document-model.tsx.

![remirror-docz@v1 0 0-rc 1 Screen Shot 2019-03-28 at 10 06 48 PM](https://user-images.githubusercontent.com/57006/55210704-0281e900-51a6-11e9-880e-efb5eb026809.png)

**Comment by ifiokjr** [comment]
@100ideas thanks for looking into this, the notes should prove extremely useful.
