### ISSUE TITLE
Should <RenderTree> use default marks consistent with @remirror/core-extensions

### ISSUE THREAD

**Issue by 100ideas** [ifiokjr/remirror#66]
## Description

The "A basic editor' example demo at [docs.remirror.org/examples/json-document-model](https://docs.remirror.org/examples/json-document-model) allows for setting `bold`, `italic`, & `underline` marks. 

`<EditorLayout />` which contains `<Remirror >` correctly shows the marks in the prosemirror [json-dom it renders](https://github.com/ifiokjr/remirror/blob/master/docs/examples/document-model.tsx#L105).

![docs remirror org Screen Shot 2019-03-27 at 3 35 01 PM](https://user-images.githubusercontent.com/57006/55118812-db93bc00-50ac-11e9-8ae7-464240561350.png)

I want to toggle between editor and rendered prosemirror dom and thought that might be what the`[<BasicRendererReact>](https://github.com/ifiokjr/remirror/blob/master/docs/examples/document-model.tsx#L113)` component in the example is for (it wraps `<RenderTree>`).

I noticed that if I pass the json-dom containing any added marks output by `<EditorLayout />` to `<BasicRendererReact>`, it complains about not understanding the mark.

I solved this by passing a `markMap` prop to `<RenderTree>` that specified the marks it didn't recognize.

Assuming `bold`, `italic`, `underline` are the mark names defined for the corresponding marks in `@remirror/core-extensions`, [should `<RenderTree>` set its defaultMarkMap](https://github.com/ifiokjr/remirror/blob/master/%40remirror/renderer-react/src/renderer.tsx#L89) to use marks with the same names?

```js
const markMap = {
  bold: 'strong',
  italic: 'em',
  // em: 'em',
  // strong: 'strong',
  code: 'code',
  link: 'a',
  underline: 'u',
};


export function BasicRendererReact() { return <RenderTree json={initialJson} /> };
export default function () { return <RenderTree json={initialJson} markMap={markMap} /> };

const initialJson = {
"type": "doc",
    "content": [
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "Better docs to come soon..."
          }
        ]
      },
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "I'm "
          },
          {
            "type": "text",
            "marks": [
              {
                "type": "bold"
              },
              {
                "type": "underline"
              }
            ],
            "text": "Bold"
          }
        ]
      },
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "However for now it is important that something is in place."
          }
        ]
      }
    ]
  }
```

https://github.com/ifiokjr/remirror/blob/master/docs/examples/document-model.tsx

One area I had to puzzle through was how to properly initialize the `<RenderTree />` json viewer. I initially copied-and-pasted the output of the `RenderTree` component as json back into my source code so I could initialize the editor with more content. However, `RenderTree` didn't know how to interpret `bold` or `italic` marks that the stock `remirror` editor generated. I eventually figured out how to [pass in a modifed `markMap`](https://gist.github.com/100ideas/9ba3aa4fffc5d44aebfbdcf1b437f286#file-textblockeditor-jsx-L137). I didn't try to hard to read all the documentation since I assumed it was in flux, so I may have missed the details about that. otherwise that info would be good to add to the docs.

## Possible Fix

set [`<RenderTree>`'s `defaultMarkMap`](https://github.com/ifiokjr/remirror/blob/master/%40remirror/renderer-react/src/renderer.tsx#L89) to the following:

```js
const markMap = {
  bold: 'strong',
  italic: 'em',
  // em: 'em',
  // strong: 'strong',
  code: 'code',
  link: 'a',
  underline: 'u',
};

**Comment by ifiokjr** [comment]
@100ideas thanks for raising this issue. One thing it highlights is just how bad the current state of documentation is for the project. Addressing this deficiency will be the priority over the coming weeks. 

Your fix looks good. If you open a PR I'll merge it straight away. I'm knee-deep in a PR of my own right now so your help would be highly appreciated. Let me know if you have any issues with the PR. It would be really useful to know how much friction there is to contributing to this project. 

### Further information

At the moment there are two ways to render a document.

The renderer is the ideal way as it allows for customization of marks and nodes, but there is also a [`ReactSerializer`](https://github.com/ifiokjr/remirror/blob/d62b06358b06d7e519a99c106007efac9e1cd87e/%40remirror/renderer-react/src/serializer.ts#L25) which enables mimicking the expected prosemirror document in react. 

This is how we're able to automate SSR. It looks through the schema and prosemirror content and automatically generates a react element tree from the `toDOM` methods in the nodes and marks. 

See a real example [here](https://github.com/ifiokjr/remirror/blob/d62b06358b06d7e519a99c106007efac9e1cd87e/%40remirror/react-ssr/src/component.tsx#L1-L18). 

https://github.com/ifiokjr/remirror/blob/d62b06358b06d7e519a99c106007efac9e1cd87e/%40remirror/react-ssr/src/component.tsx#L1-L18


**Please note:** Currently this doesn't support rendering `ReactNodeViews` but that will be addressed in a future pull request.

**Comment by ifiokjr** [comment]
Fixed in https://github.com/ifiokjr/remirror/commit/12e0d7988c2aadfa4bb803a328ce1e8862a1dccc
