### ISSUE TITLE
Missing typescript definitions

### ISSUE THREAD

**Issue by ericedouard** [ifiokjr/remirror#77]
## Description

Hi, thanks for this great project. I'm having an issue while trying to run the basic example: 

<img width="815" alt="Screenshot 2019-04-09 at 09 23 44" src="https://user-images.githubusercontent.com/19872411/55782176-036f2080-5aac-11e9-8012-422e6b2216fb.png">

It seems the packages makes reference to files located in "support", which are not exported. 

Thanks

**Comment by ifiokjr** [comment]
Thanks for raising this @ericedouard. I can fix it by moving all type patches into the packages that consume them. I'll have to look into `hoistNonReactStatics` though.

**Comment by ifiokjr** [comment]
@ericedouard as a short-term fix have you tried adding `"skipLibCheck": true,` to your `tsconfig.json` compilerOptions.

**Comment by ericedouard** [comment]
@ifiokjr  That did the trick, thanks !
Congrats on this library, it's really refreshing to see clean nice architectures like this.
