### ISSUE TITLE
Dynamically set state of prosemirror

### ISSUE THREAD

**Issue by ericedouard** [ifiokjr/remirror#78]
Hello,

I am trying to implement an editor with tabs (like vscode), for that, I would need to dynamically set the state of the prosemirror editor (when the user changes tabs). Is there anyway to do this with the current implementation of remirror?

Thanks !

**Comment by ifiokjr** [comment]
@ericedouard Controlled remirror component design is coming soon. It'll use a combination of `onStateChange` and `value` to manage the state from outside the component. 

If I could see some pseudo code for what you're currently trying to implement, it may be possible to achieve the same outcome without controlling the state.

**Comment by ericedouard** [comment]
I'm currently using SlateJS, (which works fine but has huge performance problems as soon as the document gets a little bit complex, so using slate is not possible for us. From what we have been able to test, Prosemirror seems outstanding regarding performance.)

 Essentially, the state in our editor page is as such:
```
{
    tabs: Array<value: State>,
    activeIndex: number
}
```
with State being the editor state (with cursor position, active selection etc...).

`tabs[activeIndex]` is passed as value to the slate editor. When the user changes tab, the state is automatically updated.

It seems we just need a controlled component like you suggested.
