### ISSUE TITLE
@remirror/renderer-react skipUnknownTypes behavior is reversed

### ISSUE THREAD

**Issue by hennessyevan** [ifiokjr/remirror#82]
## Description

@remirror/renderer-react throws errors if the prop is set which seems to be the opposite of the desired behavior of the prop. https://github.com/ifiokjr/remirror/blob/master/%40remirror/renderer-react/src/renderer.tsx#L128

```js
    if (skipUnknownTypes) {
      throw new Error('No handler for node type `' + json.type + '` registered');
    }
```

## Possible Fix

```js
    if (!skipUnknownTypes) {
      throw new Error('No handler for node type `' + json.type + '` registered');
    }
```
should do the trick. Let me know if you'd like a PR

**Comment by ifiokjr** [comment]
@hennessyevan good spot!
