### ISSUE TITLE
RFC: New package @remirror/extension-image

### ISSUE THREAD

**Issue by hennessyevan** [ifiokjr/remirror#88]
## Detailed Description

This issue is to track discussion for an image extension. The extension should follow the given `RemirrorExtension` api (subject to change). 

Borrowed configuration structure from https://github.com/pqina/filepond. Will possibly use `filepond` under the hood.

```tsx
<RemirrorExtension<ImageExtensionOptions>
    Constructor={Image}
    Provider={() => ({process, revert, load, restore, fetch})} />
```

## Possible Implementation

`Constructor` would handle the prosemirror schema logic.

`Provider` expects a configuration function on how to perform the network tasks necessary for the image to save the image and pass the resolved image object back to the extension to save in the document.

Image would save to the schema like:
```js
{
    type: "image",
    attrs: {
        id: "testId", // can supply an id or a url.
        url: "https://provider.url/testId.png", 
        width: 300,
        height: 200,
        alt: "optional alt tag"
     }
}
```

#### Provider API (short version)
The provider configuration would seek to emulate (if not fork) https://pqina.nl/filepond/docs/patterns/api/server/#advanced

 - **Process**: Handles uploading an image to the server and passes the `id` or `url` to remirror to save in the document. Passes the resulting file object to the extension. Also passes optional parameters to the other lifecycle methods.
 - **Revert**: Custom revert methods receive the unique server file id and a load and error callback.
 - **Load**: Custom load methods receive the local file source, and the callback methods: load, error, abort, and headers.
 - **Restore**: Custom restore methods used to restore an image from the server back into the editor. Useful when storing drafts or editing saved documents.
- **Fetch**: The custom fetch method receives the url to fetch and passes a file object to the extension

Edit: Jun-20-2019 - Added details on the lifecycle methods

**Comment by alexluong** [comment]
Hey @hennessyevan, I saw you mentioned `filepond` in the issue. I'm not sure if that means we should use it for image upload?

I wonder if there's any way we can build an image extension without being opinionated about how the image is uploaded/sourced.

For example, if the extension is built upon `filepond`, what if I want the image from a url? Do I need to rebuild the extension in that case?

**Comment by hennessyevan** [comment]
@alexluong Yeah, I'm just borrowing `filepond`'s configuration API syntax because it's well thought out. You can read more about that here: https://pqina.nl/filepond/docs/patterns/api/server/#advanced

The provider prop exposes some lifecycle methods that act as a configuration. It doesn't assume anything about how you want to handle the network logic. It lets you "bring-your-own" image provider. The `process, revert, load, restore, fetch` refer to various stages in the image's lifecycle.

The motivation behind using the same API as `filepond` is of course that if we don't have to reinvent the wheel.

To answer your example: Simply fetching from a URL would like something this (in a simple way):
```tsx
<RemirrorExtension
  Constructor={Image}
  Provider={() => ({
      // Return the configured fetch method
      fetch: (url, load) => {
          // Use fetch/XHR or whatever you'd like then pass the blob to the load method
          fetch(url).then(res => res.blob()).then(image => load(image))
      }
  })
} />
```

Of course if there are any big reservations to using this system let me know. The [Atlaskit editor](https://atlaskit.atlassian.com/packages/editor/editor-core) does something similar to this

**Comment by ifiokjr** [comment]
Okay, I'm now visiting this.

The API feels stable enough to begin working on a general case `@remirror/extension-image` package.

**Comment by hennessyevan** [comment]
Just as an update to this, I know it's been a while but I'm currently working on this extension internally in an app and will publish as an extension when it's done 👍

**Comment by ifiokjr** [comment]
@hennessyevan nice!

**Comment by hboylan** [comment]
Great work on the library guys. I was able to drag-n-drop images in with the newly minted `@remirror/extension-image` so this issue could likely be closed.

Additional image features I'd like to see are:
- image resize
- image import menu button
  - from URL
  - from computer

I really like the way [this](http://cdn.summitlearning.org/assets/czi_prosemirror_0_0_1_1_20181129151434_index.html) `prosemirror` implementation handles images. Let me know how I can help out. Still getting aquainted with `remirror`, but would love to contribute a PR for this.

**Comment by hennessyevan** [comment]
Yeah @hboylan I haven't used that extension yet actually, I'd rather bring some of what I've been working on to this extension rather than strip mine down to be more generic. If you open a PR I'd be willing to help get those features under way.
